<?php
/**
 * VRPay Magento 2
 *
 * This Magento 2 extension enables to process payments with VRPay (https://www.vr-payment.de).
 *
 * @package VRPayment_Payment
 * @author VR Payment GmbH (https://www.vr-payment.de)
 * @license http://www.apache.org/licenses/LICENSE-2.0  Apache Software License (ASL 2.0)

 */

/** @var $block \VRPayment\Payment\Block\DeviceSession */
?>
<script type="text/x-magento-init">
{
    "*": {
        "VRPayment_Payment/js/vrpayment-device": {
            "scriptUrl" : "<?=$block->escapeHtml($block->getScriptUrl())?>",
            "identifierUrl" : "<?=$block->escapeHtml($block->getSessionIdentifierUrl())?>"
        }
    }
}
</script>