<?php
/**
 * VR Payment Magento 2
 *
 * This Magento 2 extension enables to process payments with VR Payment (https://www.vr-payment.de).
 *
 * @package VRPayment_Payment
 * @author VR Payment GmbH (https://www.vr-payment.de)
 * @license http://www.apache.org/licenses/LICENSE-2.0  Apache Software License (ASL 2.0)

 */
/**
 * @formatter:off
 */

/** @var $block \VRPayment\Payment\Block\Adminhtml\Sales\Order\Invoice\View */
?>

<?php if ($block->isCapturePending()) : ?>
	<div class="messages">
		<div class="message message-warning warning">
			<?=$block->escapeHtml(\__('The capture has been requested but could not be completed yet. The invoice will be updated, as soon as the capture is done.'))?>
		</div>
	</div>
<?php endif; ?>