<?php
/**
 * VRPay Magento 2
 *
 * This Magento 2 extension enables to process payments with VRPay (https://www.vr-payment.de).
 *
 * @package VRPayment_Payment
 * @author VR Payment GmbH (https://www.vr-payment.de)
 * @license http://www.apache.org/licenses/LICENSE-2.0  Apache Software License (ASL 2.0)

 */
/**
 * @formatter:off
 */

/** @var $block \VRPayment\Payment\Block\Adminhtml\Sales\Order\View */
?>

<?php if ($block->hasPendingRefund()) : ?>
	<div class="messages">
		<div class="message message-warning warning">
			<?=$block->escapeHtml(\__('This order has a pending refund request.'))?>
			<a class="message-link" href="<?=$block->escapeHtml($block->getRefundUrl())?>"><?=$block->escapeHtml(\__('Send Refund Request'))?></a>
		</div>
	</div>
<?php endif; ?>